version: 1
services:
  - type: web
    name: Timesheet-app
    env: python
    plan: free  # You can change this if you are on a paid plan
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput  
    startCommand: "gunicorn timesheet_project.wsgi:application --bind 0.0.0.0:10000"
    port: 10000
